---
title: "quarto-check"
---

### Output of quarto check

\$ quarto check Quarto 1.6.39

\[\>\] Checking versions of quarto binary dependencies... Pandoc version 3.4.0: OK Dart Sass version 1.70.0: OK Deno version 1.46.3: OK Typst version 0.11.0: OK \[\>\] Checking versions of quarto dependencies......OK

\[\>\] Checking Quarto installation......OK Version: 1.6.39 Path: C:\Users\...\AppData\Local\Programs\Quarto\bin CodePage: 1252

\[\>\] Checking tools....................OK TinyTeX: (not installed) Chromium: (not installed)

\[\>\] Checking LaTeX....................OK Tex: (not detected)

\[\>\] Checking basic markdown render....OK

\[\>\] Checking Python 3 installation....(None)

```         
  Unable to locate an installed version of Python 3.
  Install Python 3 from https://www.python.org/downloads/
```

\[\>\] Checking R installation...........OK Version: 4.2.2 Path: C:/PROGRA~1/R/R-42~1.2 LibPaths: - C:/Users/.../AppData/Local/R/win-library/4.2 - C:/Program Files/R/R-4.2.2/library knitr: 1.49 rmarkdown: 2.29

\[\>\] Checking Knitr engine render......OK

### IDE

RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
